# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Playwright CI

on:
  push:
    branches: [ master, playwright ]
  pull_request:
    branches: [ master, playwright ]

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - uses: microsoft/playwright-github-action@v1
    - run: npm ci
    - run: npm run build --if-present
    - run: bin/test-server.rb
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: jest-report
        path: jest-report.json

